import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { useGame } from '../../context/GameContext';
import { Zap, Users, Scale, Shield, Coins, Trophy } from 'lucide-react';
import { LeaderboardView } from '../game/LeaderboardView';

export const StatsGlossaryModal: React.FC<{ isOpen: boolean; onClose: () => void }> = ({ isOpen, onClose }) => {
  const { state } = useGame();
  const [showLeaderboard, setShowLeaderboard] = React.useState(false);

  const STATS = [
    {
      id: 'awe',
      label: 'Awe',
      icon: <Zap size={18} className="text-amber-400" />,
      value: state.meters.awe,
      desc: "The spiritual energy and mystery of your group. High Awe attracts new followers but decays faster as you become legitimate. Increase: Rituals (especially Incense) and material culture upgrades.",
    },
    {
      id: 'cohesion',
      label: 'Cohesion',
      icon: <Users size={18} className="text-emerald-400" />,
      value: state.meters.cohesion,
      desc: "How tightly bound your members are. High Cohesion prevents schisms and speeds up congregation growth. Increase: Chant ritual and socializing disciples in the Teach tab.",
    },
    {
      id: 'legitimacy',
      label: 'Legitimacy',
      icon: <Scale size={18} className="text-blue-400" />,
      value: state.meters.legitimacy,
      desc: "How the secular world and the state perceive you. Required for institutional evolution but weighs down spiritual Awe. Increase: Boundary Maintenance in Sorting, approving documents in Admin, and stage evolution.",
    },
    {
      id: 'purity',
      label: 'Purity',
      icon: <Shield size={18} className="text-purple-400" />,
      value: state.meters.purity,
      desc: "Commitment to the group's strict boundaries. If Purity hits zero, internal infighting will dissolve the Sanctuary. Increase: Sacred Sorting (Classification) and the Meditate ritual.",
    },
    {
      id: 'resources',
      label: 'Resources',
      icon: <Coins size={18} className="text-yellow-600" />,
      value: state.resources,
      isRaw: true,
      desc: "Earthly wealth and materials. Generated by the congregation and certain disciples. Needed for upgrades and evolution. Increase: Passive income from congregation (1 per 10 members) and Steward disciples.",
    },
  ];

  return (
    <AnimatePresence>
      {isOpen && (
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={() => { onClose(); setShowLeaderboard(false); }}
        className="fixed inset-0 z-[150] flex items-center justify-center bg-black/90 backdrop-blur-md p-4 overflow-y-auto"
      >
        <motion.div
          initial={{ scale: 0.9, y: 20 }}
          animate={{ scale: 1, y: 0 }}
          exit={{ scale: 0.9, y: 20 }}
          onClick={(e) => e.stopPropagation()}
          className="bg-slate-900 border border-slate-800 rounded-3xl p-5 max-w-sm w-full shadow-2xl relative my-auto"
        >
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-serif text-amber-100">
              Sociological Indicators
            </h3>
            <button onClick={onClose} className="text-slate-600 hover:text-slate-400 text-xs uppercase tracking-widest">
              Close
            </button>
          </div>

          <div className="space-y-4">
            {STATS.map(stat => (
              <div key={stat.id} className="flex gap-3 items-start">
                <div className="w-9 h-9 rounded-xl bg-slate-800 border border-slate-700 flex items-center justify-center shrink-0">
                  {stat.icon}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex justify-between items-center mb-0.5">
                    <span className="font-bold text-sm text-slate-200">{stat.label}</span>
                    <span className="font-mono text-xs text-amber-500 bg-amber-500/10 px-2 py-0.5 rounded-full border border-amber-500/20">
                      {stat.isRaw ? Math.round(stat.value) : `${Math.round(stat.value)}%`}
                    </span>
                  </div>
                  <p className="text-[10px] text-slate-500 leading-relaxed italic">
                    {stat.desc}
                  </p>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-4 pt-4 border-t border-slate-800">
            {showLeaderboard ? (
              <div className="h-64 overflow-y-auto -mx-2 rounded-xl">
                <LeaderboardView />
              </div>
            ) : (
              <button
                onClick={(e) => { e.stopPropagation(); setShowLeaderboard(true); }}
                className="w-full py-2.5 flex items-center justify-center gap-2 text-xs text-slate-400 hover:text-amber-400 transition-colors"
              >
                <Trophy size={14} /> View Leaderboard
              </button>
            )}
          </div>
        </motion.div>
      </motion.div>
      )}
    </AnimatePresence>
  );
};
